# Generated by Django 6.0 on 2026-01-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_interviewquestion_is_approved_pdf_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='is_approved',
        ),
    ]
