# Generated by Django 6.0 on 2026-01-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserUpload',
        ),
    ]
