# Generated by Django 6.0 on 2026-01-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_userupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdf',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
