# Generated by Django 6.0.1 on 2026-01-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_interviewquestion_is_approved_pdf_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdf',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
