# Generated by Django 6.0.1 on 2026-01-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_interviewquestion_download_count_pdf_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdf',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
