# Generated by Django 6.0 on 2026-01-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='uploaded_at',
        ),
    ]
